### ISSUE TITLE
Doubt regarding callable integer in Hamiltonian functions

### ISSUE THREAD

**Issue by Marioherreroglez** [ITensor/ITensorNetworks.jl#202]
I am trying to understand why we need to make parameters for the Hamiltonians callable and hence depend on the graph. I want to define three-body terms (actual node, nearest neighbor node, and next nearest neighbor), should I make the parameters depend also on these (below)?

```
function haldane(g::AbstractGraph; J=1, h₁=0, h₂=0)
    (; J, h₁, h₂) = map(to_callable, (;J, h₁, h₂))
    ℋ = OpSum()
    for e in edges(g)
      for nextnn in next_nearest_neighbors(g, dst(e))
        ℋ -= J(e,nextnn) , "Sz", src(e), "Sx", dst(e),  "Sx", nextnn
      end
      #Other terms go here
    end
  return ℋ
  end
  ```

What would be the implications of skipping the callable part as shown below?

```
function haldane(g::AbstractGraph; J=1, h₁=0, h₂=0)
    ℋ = OpSum()
    for e in edges(g)
      for nextnn in next_nearest_neighbors(g, dst(e))
        ℋ -= J , "Sz", src(e), "Sx", dst(e),  "Sx", nextnn
      end
      #Other terms go here
    end
  return ℋ
  end
  ```

**Comment by emstoudenmire** [comment]
Hi Mario,
This sounds like a support question versus an issue. Could you please post this question on our support forum at https://itensor.discourse.group ? Also when you post, could you please say which file contains the code you are referring to above, to give more context? Thanks.

**Comment by mtfishman** [comment]
@Marioherreroglez agreed with Miles that if something is more of a question rather than an issue or feature request it should be posted on the support forum rather than on Github.

As a short answer, this allows for users to pass either numbers as parameters, in which case they are treated as uniform couplings and fields, or as a function of the edges and vertices in the case of non-uniform couplings and fields.

In the simplest case, if the couplings and fields are constants, you can just pass numbers, and the conversion to a callable is just an internal detail that you don't have to worry about.

**Comment by mtfishman** [comment]
This question was reposted and answered here: https://itensor.discourse.group/t/itensornetworks-callable-hamiltonian-parameters/2031.
